version: '3'
services:
  app:
    #build: .
    image: php:apache-bullseye
    volumes:
      - ./app:/var/www/html
    labels:
      - "traefik.frontend.rule=Host:mazemaster"
      - "traefik.enable=true"
    ports:
      - 80:80
  
  database:
    image: mariadb
    volumes:
      - ./app/assets/database/dumb.sql:/docker-entrypoint-initdb.d/dumb.sql
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mazemaster
    ports:
      - 3306:3306

volumes:
  database-data: